import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import theme from "@/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vitor Silva - Desenvolvedor Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ background: theme.bg, paddingBottom: "2rem" }}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
